### ISSUE TITLE
Add Bin property to ApiServices.Cards.ResponseModels.Card

### ISSUE THREAD

**Issue by nlopezcenteno** [CKOTech/checkout-net-library#18]
Hi, Could be possible to add the Bin property to Checkout.ApiServices.Cards.ResponseModels.Card?

**Comment by marc-roberts-cko** [comment]
Hi Nelson! Thanks for your interest in our .NET library. We actively encourage users to contribute to the library, so if you like, feel free to fork the library, make the change, and submit a pull request.

Otherwise, happy to get one of our devs to add the property. Let me know if you'd like to contribute :)

Cheers,
Marc

**Comment by nlopezcenteno** [comment]
Hi Marc, OK I will do the pull request.

**Comment by helder-goncalves-cko** [comment]
Hi Nelson!

Thanks for the pull request.
We've included your changes in the latest version of the [Checkout.ApiClient](https://www.nuget.org/packages/Checkout.ApiClient/1.3.0.6).

Cheers,
Hélder
